# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Check and build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java_version: ["8", "11", "15"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK v${{ matrix.java_version}}
      uses: actions/setup-java@v2
      with:
        distribution: "adopt"
        java-version: ${{ matrix.java_version }}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Check code
      run: ./gradlew clean check

    - name: Build code
      run: ./gradlew clean jar
